# Generated by Django 5.2.7 on 2025-11-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=150)),
                ('costo', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='actividades/')),
                ('destacada', models.BooleanField(default=False)),
            ],
        ),
    ]
